import "@/styles/globals.css";

import localFont from "next/font/local";
// import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import ProtectedRoute from "./_components/protectedRoute";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontFarsi = localFont({
  src: "./IRAN_SemiBold.woff2",
  variable: "--font-farsi",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // <html lang="en" className={`${GeistSans.variable}`}>
    <html
      suppressHydrationWarning
      dir="rtl"
      lang="fr"
      className={`${fontFarsi.variable}`}
    >
      <body className="font-farsi">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
